services:
  gotask:
    hostname: gotask
    container_name: gotask
    build:
      context: .
      args:
        VERSION: ${VERSION}
    ports:
      - "8080:8080"
    expose:
      - 3306
    depends_on:
      - mysql
  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:8.4
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./deployments/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: h74geif54j
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5
