services:
  mysql:
    container_name: mysql-container
    image: mysql:8.4
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./deployments/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: h74geif54j
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
